### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by daissi** [PhanstielLab/CORALp#1]
Part of JOSS review (https://github.com/openjournals/joss-reviews/issues/1837):

Could you add installation instructions? There is a list of R packages dependencies but no information about the installation of CoralP itself. Would be good as well to convert it to an R package [1-2].

[1] https://cran.r-project.org/doc/manuals/r-release/R-exts.html
[2] http://r-pkgs.had.co.nz/

**Comment by dphansti** [comment]
Thanks so much for your feedback. We agree that it would be helpful to provide more detailed instructions for running the code locally. So we have added a new section to the README called “Running Locally” that provides information and code for downloading the code, installing prerequisites, and running the app locally.

I am not sure if it makes sense to turn it into an R package. Packages are typically collections of functions. But Coralp is a Shiny application that has been designed to run through a browser. As such Shiny apps are not typically distributed as packages. To do so would be unusual and wouldn’t be any easier than simply following the instructions to run locally.

**Comment by daissi** [comment]
Thanks
