### ISSUE TITLE
Typo in paper

### ISSUE THREAD

**Issue by daissi** [PhanstielLab/CORALp#2]
Part of JOSS review (openjournals/joss-reviews#1837):

Could you fix the legend of figure 1? i.e.: "Figure 1: Figure1. ....", there is a duplication of "Figure 1".

There is also a problem with the reference Bailey2015-ft which is not considered during the generation of the pdf.

**Comment by cwenger** [comment]
Fixed by https://github.com/PhanstielLab/coralp/commit/171b45d22642240322eebb164775bb184a1361c0.
