### ISSUE TITLE
locally running error  

### ISSUE THREAD

**Issue by HIM72** [PhanstielLab/CORALp#3]
I am trying to run the shiny app from my mac locally.
when I type the command I get the following.  Can you tell me why I am getting this error?
Thank you.

    > shiny::runApp()
    Loading required package: shiny
    
    Attaching package: ‘shinydashboard’
    
    The following object is masked from ‘package:graphics’:
    
        box
    
    Linking to librsvg 2.48.4
    
    Attaching package: ‘colourpicker’
    
    The following object is masked from ‘package:shiny’:
    
        runExample
    
    Attaching package: ‘DT’
    
    The following objects are masked from ‘package:shiny’:
    
        dataTableOutput, renderDataTable
    
    Attaching package: ‘jsonlite’
    
    The following object is masked from ‘package:shiny’:
    
        validate
    
    Error in dots_list(...) : object 'outputjsonshort' not found

**Comment by cwenger** [comment]
Hi @HIM72, should be fixed now. Thanks for the report.
