### ISSUE TITLE
Error message when searching in shinyapp.

### ISSUE THREAD

**Issue by HIM72** [PhanstielLab/CORALp#4]
When I type in a string in the search box I get the following error message window popup. It also shows the same message when I click the sort arrow in the column.

`DataTables warning: table id=DataTables_Table_17 - Error in tolower(x): invalid input 'Protein Phosphatase 1 Catalytic Subunit Beta<ca>' in 'utf8towcs'`

**Comment by cwenger** [comment]
@HIM72 Should be fixed. Thanks for another bug report!
